staff/config/routes.rb
Rails.application.routes.draw do


  controller :sessions do
    get 'login' => :new #get 'sessions/new'
    post 'login' => :create #get 'sessions/create'
    delete 'logout' => :destroy #get 'sessions/destroy'
  end

  get 'login', to: 'sessions#new'

  resources :users
  resources :settings
  resources :decision_files
  get '/create_decision_files/:school_teacher_response',
    to: 'decision_files#create_decision_files',
    as: 'create_decision_files'
  get '/decision_files/:decision_file/download',
    to: 'decision_files#download',
    as: 'download_decision'

  resources :request_support_documents
  resources :school_teacher_responses
  resources :response_specifications
  get '/response_specification/:id/download',
    to: 'response_specifications#download',
    as: 'download_response_specification'

  get '/school_teachers/new_all'
  post '/school_teachers/new_all', 
    to: 'school_teachers#create_all'

  resources :school_teacher_requests
  get '/school_teacher_requests/:id/add_support_document',
    to: "school_teacher_requests#add_support_document",
    as: "add_support_document"
  resources :request_specifications
  resources :school_class_lessons
  resources :school_class_students
  resources :school_students
  resources :student_bus_cards
  resources :student_photos
  resources :student_residence_addresses
  resources :student_residence_towns
  resources :student_personal_mobiles
  resources :student_parent_mobiles
  resources :student_contact_infos
  resources :students
  get 'log_books/index'

  get 'schedule/save_form'
  post 'schedule/save'
  get 'schedule/diff'
  post 'schedule/diff'
  get 'schedule/index'
  get 'schedule/diff_general'
  get '/people/phones', to: 'people#phones'

  resources :saved_school_course_teachers
  resources :saved_school_courses
  resources :school_teachers
  resources :school_course_teachers
  resources :school_courses
  resources :teacher_specialties
  resources :teachers
  resources :people
  resources :school_classes
  resources :lesson_assignments
  resources :lessons
  resources :lesson_types
  resources :school_grade_specialties
  resources :school_grades
  resources :schoolyears
  resources :schools
  resources :specialties
  resources :teacher_working_classes
  # For details on the DSL available within this file, see 
  # http://guides.rubyonrails.org/routing.html
  #
  resources :school_classes do
    member do
      get 'duplicate'
    end
  end

  get '/pick_school', to: 'personel_processor#pick_school'
  get '/pick_teacher/:school_id', 
    to: 'personel_processor#pick_teacher',
    as: "pick_teacher_for"

  get '/pick_lessons/:teacher_id/show_status/:school_id', 
    to: 'personel_processor#show_status',
    as: 'pick_lessons_for'

  post '/pick_lessons/:teacher_id/register/:school_id',
    to: 'personel_processor#register_lessons',
    as: 'register_these_lessons_for'

  delete 'pick_lessons/:teacher_id/remove/:school_id/:school_course_id',
    to: 'personel_processor#unregister_lessons',
    as: 'unregister_from'

  get '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#show_all',
    as: 'pick_unassigned_lessons_for'

  post '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#register_unassigned_lessons',
    as: 'register_these_unassigned_lessons_for'


  root 'personel_processor#pick_school'

  get '/homepage/:teacher_id/school/:school_id', 
    to: 'personel_processor#homepage',
    as: 'school_teacher_homepage'

  get '/homepage/:teacher_id/school/:school_id/select_request', 
    to: 'personel_processor#select_request_type',
    as: 'select_request_type'



  #requests
  get '/request/history/:school_teacher_id',
    to: 'school_teacher_requests#history',
    as: 'history_of_requests'

  get '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#apply_new',
    as: 'apply_request'

  post '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#create_request',
    as: 'create_request'

  get '/school_teacher_request/:school_teacher_request/download',
    to: 'school_teacher_requests#download',
    as: 'download_request'




  get '/reports', to: 'reports#index'
  get '/reports/classes', to: 'reports#school_classes_report'
  get '/reports/teachers', to: 'reports#school_teachers_report'
  get '/reports/teachers/lessons', to: 'reports#lessons_per_teacher'
  get '/reports/classes/registered_lessons', to: 'reports#registered_lessons_per_class'
  get '/reports/classes/unregistered_lessons', to: 'reports#unregistered_lessons_per_class'

  #get '/pick_teacher/:school_id', 
    #to: 'personel_processor#pick_teacher',
    #as: "pick_teacher_for"
end

staff/app/models/school.rb
class School < ApplicationRecord
  def to_s
    "[#{code}] #{title}"
  end
end

staff/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:code, :title, :email)
    end
end

staff/app/helpers/schools_helper.rb
module SchoolsHelper
end

staff/app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :school_code %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :school_title %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :school_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff/app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

staff/app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Title</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.code %></td>
        <td><%= school.title %></td>
        <td><%= school.email %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

staff/app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

staff/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @school.code %>
</p>

<p>
  <strong>Title:</strong>
  <%= @school.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>