staff/config/routes.rb
Rails.application.routes.draw do


  controller :sessions do
    get 'login' => :new #get 'sessions/new'
    post 'login' => :create #get 'sessions/create'
    delete 'logout' => :destroy #get 'sessions/destroy'
  end

  get 'login', to: 'sessions#new'

  resources :users
  resources :settings
  resources :decision_files
  get '/create_decision_files/:school_teacher_response',
    to: 'decision_files#create_decision_files',
    as: 'create_decision_files'
  get '/decision_files/:decision_file/download',
    to: 'decision_files#download',
    as: 'download_decision'

  resources :request_support_documents
  resources :school_teacher_responses
  resources :response_specifications
  get '/response_specification/:id/download',
    to: 'response_specifications#download',
    as: 'download_response_specification'

  get '/school_teachers/new_all'
  post '/school_teachers/new_all', 
    to: 'school_teachers#create_all'

  resources :school_teacher_requests
  get '/school_teacher_requests/:id/add_support_document',
    to: "school_teacher_requests#add_support_document",
    as: "add_support_document"
  resources :request_specifications
  resources :school_class_lessons
  resources :school_class_students
  resources :school_students
  resources :student_bus_cards
  resources :student_photos
  resources :student_residence_addresses
  resources :student_residence_towns
  resources :student_personal_mobiles
  resources :student_parent_mobiles
  resources :student_contact_infos
  resources :students
  get 'log_books/index'

  get 'schedule/save_form'
  post 'schedule/save'
  get 'schedule/diff'
  post 'schedule/diff'
  get 'schedule/index'
  get 'schedule/diff_general'
  get '/people/phones', to: 'people#phones'

  resources :saved_school_course_teachers
  resources :saved_school_courses
  resources :school_teachers
  resources :school_course_teachers
  resources :school_courses
  resources :teacher_specialties
  resources :teachers
  resources :people
  resources :school_classes
  resources :lesson_assignments
  resources :lessons
  resources :lesson_types
  resources :school_grade_specialties
  resources :school_grades
  resources :schoolyears
  resources :schools
  resources :specialties
  resources :teacher_working_classes
  # For details on the DSL available within this file, see 
  # http://guides.rubyonrails.org/routing.html
  #
  resources :school_classes do
    member do
      get 'duplicate'
    end
  end

  get '/pick_school', to: 'personel_processor#pick_school'
  get '/pick_teacher/:school_id', 
    to: 'personel_processor#pick_teacher',
    as: "pick_teacher_for"

  get '/pick_lessons/:teacher_id/show_status/:school_id', 
    to: 'personel_processor#show_status',
    as: 'pick_lessons_for'

  post '/pick_lessons/:teacher_id/register/:school_id',
    to: 'personel_processor#register_lessons',
    as: 'register_these_lessons_for'

  delete 'pick_lessons/:teacher_id/remove/:school_id/:school_course_id',
    to: 'personel_processor#unregister_lessons',
    as: 'unregister_from'

  get '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#show_all',
    as: 'pick_unassigned_lessons_for'

  post '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#register_unassigned_lessons',
    as: 'register_these_unassigned_lessons_for'


  root 'personel_processor#pick_school'

  get '/homepage/:teacher_id/school/:school_id', 
    to: 'personel_processor#homepage',
    as: 'school_teacher_homepage'

  get '/homepage/:teacher_id/school/:school_id/select_request', 
    to: 'personel_processor#select_request_type',
    as: 'select_request_type'



  #requests
  get '/request/history/:school_teacher_id',
    to: 'school_teacher_requests#history',
    as: 'history_of_requests'

  get '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#apply_new',
    as: 'apply_request'

  post '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#create_request',
    as: 'create_request'

  get '/school_teacher_request/:school_teacher_request/download',
    to: 'school_teacher_requests#download',
    as: 'download_request'




  get '/reports', to: 'reports#index'
  get '/reports/classes', to: 'reports#school_classes_report'
  get '/reports/teachers', to: 'reports#school_teachers_report'
  get '/reports/teachers/lessons', to: 'reports#lessons_per_teacher'
  get '/reports/classes/registered_lessons', to: 'reports#registered_lessons_per_class'
  get '/reports/classes/unregistered_lessons', to: 'reports#unregistered_lessons_per_class'

  #get '/pick_teacher/:school_id', 
    #to: 'personel_processor#pick_teacher',
    #as: "pick_teacher_for"
end

staff/app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :person
  belongs_to :school
  belongs_to :teacher_working_class
  has_many :teacher_specialties

  def full_name
    person.last_name + " " + person.first_name
  end

  def to_s
    toReturn = full_name
    teacher_specialties.each do |teacher_specialty|
      toReturn += " "+ teacher_specialty.specialty.code
    end
    return toReturn
  end
end

staff/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:person_id, :school_id, 
                                      :date_in_school, 
                                      :date_employed, 
                                      :teaching_hours,
                                      :teacher_working_class_id,
                                     )
    end
end

staff/app/helpers/teachers_helper.rb
module TeachersHelper
end

staff/app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Επιλογή προσωπικού" %>
    <%= form.collection_select :person_id,
    Person.order(:last_name), :id, :full_name, 
    include_blank: false, prompt:true %>
  </div>

  <div class="field">
    <%= form.label "Σχολείο οργανικής θέσης ή τοποθέτησης" %>
    <%= form.collection_select :school_id,
    School.order(:title), :id, :title, 
    include_blank: false, prompt:true %>
  </div>

  <div class="field">
    <%= form.label "Σχέση εργασίας" %>
    <%= form.collection_select :teacher_working_class_id,
    TeacherWorkingClass.order(:id), :id, :description, 
    include_blank: false, prompt:true %>
  </div>

  <div class="field">
    <%= form.label "Ημερομηνία προσέλευσης στο σχολείο (προαιρετικό)." %>
    <%= form.date_select :date_in_school, id: :teacher_date_in_school,
      start_year: 1950 %>
  </div>

  <div class="field">
    <%= form.label "Ημερομηνία διορισμού (προαιρετικό)." %>
    <%= form.date_select :date_employed, id: :teacher_date_employed,
      start_year: 1950 %>
  </div>

  <div class="field">
    <%= form.label "Διδακτικό ωράριο" %>
    <%= form.number_field :teaching_hours, id: :teacher_teaching_hours %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff/app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

staff/app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Προσωπικό</th>
      <th>Σχολείο</th>
      <th>Σχέση εργασίας</th>
      <th>Ημ. Ανάλ. Υπ. στο Σχολείο</th>
      <th>Ημ. Διορισμού</th>
      <th>Teaching hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.person.last_name %></td>
        <td><%= teacher.school.title %></td>
        <td><%= teacher.teacher_working_class.description %></td>
        <td><%= teacher.date_in_school %></td>
        <td><%= teacher.date_employed %></td>
        <td><%= teacher.teaching_hours %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

staff/app/views/teachers/new.html.erb
<h1>Ορισμός προσωπικού ως καθηγητή / καθηγήτρια</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

staff/app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Προσωπικό:</strong>
  <%= @teacher.person.last_name %>
</p>

<p>
  <strong>Σχολείο:</strong>
  <%= @teacher.school.title %>
</p>

<p>
  <strong>Σχέση εργασίας:</strong>
  <%= @teacher.teacher_working_class.description %>
</p>

<p>
  <strong>Ημερομηνία ανάληψης υπηρεσίας στο παραπάνω σχολείο:</strong>
  <%= @teacher.date_in_school %>
</p>

<p>
  <strong>Ημερομηνία ανάληψης υπηρεσίας:</strong>
  <%= @teacher.date_employed %>
</p>

<p>
  <strong>Διδακτικό ωράριο:</strong>
  <%= @teacher.teaching_hours %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>