staff/config/routes.rb
Rails.application.routes.draw do


  controller :sessions do
    get 'login' => :new #get 'sessions/new'
    post 'login' => :create #get 'sessions/create'
    delete 'logout' => :destroy #get 'sessions/destroy'
  end

  get 'login', to: 'sessions#new'

  resources :users
  resources :settings
  resources :decision_files
  get '/create_decision_files/:school_teacher_response',
    to: 'decision_files#create_decision_files',
    as: 'create_decision_files'
  get '/decision_files/:decision_file/download',
    to: 'decision_files#download',
    as: 'download_decision'

  resources :request_support_documents
  resources :school_teacher_responses
  resources :response_specifications
  get '/response_specification/:id/download',
    to: 'response_specifications#download',
    as: 'download_response_specification'

  get '/school_teachers/new_all'
  post '/school_teachers/new_all', 
    to: 'school_teachers#create_all'

  resources :school_teacher_requests
  get '/school_teacher_requests/:id/add_support_document',
    to: "school_teacher_requests#add_support_document",
    as: "add_support_document"
  resources :request_specifications
  resources :school_class_lessons
  resources :school_class_students
  resources :school_students
  resources :student_bus_cards
  resources :student_photos
  resources :student_residence_addresses
  resources :student_residence_towns
  resources :student_personal_mobiles
  resources :student_parent_mobiles
  resources :student_contact_infos
  resources :students
  get 'log_books/index'

  get 'schedule/save_form'
  post 'schedule/save'
  get 'schedule/diff'
  post 'schedule/diff'
  get 'schedule/index'
  get 'schedule/diff_general'
  get '/people/phones', to: 'people#phones'

  resources :saved_school_course_teachers
  resources :saved_school_courses
  resources :school_teachers
  resources :school_course_teachers
  resources :school_courses
  resources :teacher_specialties
  resources :teachers
  resources :people
  resources :school_classes
  resources :lesson_assignments
  resources :lessons
  resources :lesson_types
  resources :school_grade_specialties
  resources :school_grades
  resources :schoolyears
  resources :schools
  resources :specialties
  resources :teacher_working_classes
  # For details on the DSL available within this file, see 
  # http://guides.rubyonrails.org/routing.html
  #
  resources :school_classes do
    member do
      get 'duplicate'
    end
  end

  get '/pick_school', to: 'personel_processor#pick_school'
  get '/pick_teacher/:school_id', 
    to: 'personel_processor#pick_teacher',
    as: "pick_teacher_for"

  get '/pick_lessons/:teacher_id/show_status/:school_id', 
    to: 'personel_processor#show_status',
    as: 'pick_lessons_for'

  post '/pick_lessons/:teacher_id/register/:school_id',
    to: 'personel_processor#register_lessons',
    as: 'register_these_lessons_for'

  delete 'pick_lessons/:teacher_id/remove/:school_id/:school_course_id',
    to: 'personel_processor#unregister_lessons',
    as: 'unregister_from'

  get '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#show_all',
    as: 'pick_unassigned_lessons_for'

  post '/pick_lessons/:teacher_id/pick_not_assigned/:school_id',
    to: 'personel_processor#register_unassigned_lessons',
    as: 'register_these_unassigned_lessons_for'


  root 'personel_processor#pick_school'

  get '/homepage/:teacher_id/school/:school_id', 
    to: 'personel_processor#homepage',
    as: 'school_teacher_homepage'

  get '/homepage/:teacher_id/school/:school_id/select_request', 
    to: 'personel_processor#select_request_type',
    as: 'select_request_type'



  #requests
  get '/request/history/:school_teacher_id',
    to: 'school_teacher_requests#history',
    as: 'history_of_requests'

  get '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#apply_new',
    as: 'apply_request'

  post '/request/:school_teacher_id/:request_specification_id',
    to: 'school_teacher_requests#create_request',
    as: 'create_request'

  get '/school_teacher_request/:school_teacher_request/download',
    to: 'school_teacher_requests#download',
    as: 'download_request'




  get '/reports', to: 'reports#index'
  get '/reports/classes', to: 'reports#school_classes_report'
  get '/reports/teachers', to: 'reports#school_teachers_report'
  get '/reports/teachers/lessons', to: 'reports#lessons_per_teacher'
  get '/reports/classes/registered_lessons', to: 'reports#registered_lessons_per_class'
  get '/reports/classes/unregistered_lessons', to: 'reports#unregistered_lessons_per_class'

  #get '/pick_teacher/:school_id', 
    #to: 'personel_processor#pick_teacher',
    #as: "pick_teacher_for"
end

staff/app/controllers/school_teacher_responses_controller.rb
class SchoolTeacherResponsesController < ApplicationController
  before_action :set_school_teacher_response, only: [:show, :edit, :update, :destroy]

  # GET /school_teacher_responses
  # GET /school_teacher_responses.json
  def index
    @open_school_teacher_requests = SchoolTeacherRequest.find_by_sql("select * from school_teacher_requests "+
                                                                     "where id not in "+
                                                                     "(select school_teacher_request_id from school_teacher_responses);")
    @school_teacher_responses = SchoolTeacherResponse.all
    @school_teacher_responses_with_decision_files = SchoolTeacherResponse.joins(:decision_file)
    @open_school_teacher_responses = @school_teacher_responses - @school_teacher_responses_with_decision_files
  end

  # GET /school_teacher_responses/1
  # GET /school_teacher_responses/1.json
  def show
    @request_support_documents = 
      RequestSupportDocument.where( school_teacher_request: 
                                   @school_teacher_response.school_teacher_request ).order( :order )
  end

  # GET /school_teacher_responses/new
  def new
    @school_teacher_response = SchoolTeacherResponse.new
  end

  # GET /school_teacher_responses/1/edit
  def edit
  end

  # POST /school_teacher_responses
  # POST /school_teacher_responses.json
  def create
    @school_teacher_response = SchoolTeacherResponse.new(school_teacher_response_params)

    respond_to do |format|
      if @school_teacher_response.save
        format.html { redirect_to @school_teacher_response, notice: 'School teacher response was successfully created.' }
        format.json { render :show, status: :created, location: @school_teacher_response }
      else
        format.html { render :new }
        format.json { render json: @school_teacher_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_teacher_responses/1
  # PATCH/PUT /school_teacher_responses/1.json
  def update
    respond_to do |format|
      if @school_teacher_response.update(school_teacher_response_params)
        format.html { redirect_to @school_teacher_response, notice: 'School teacher response was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_teacher_response }
      else
        format.html { render :edit }
        format.json { render json: @school_teacher_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_teacher_responses/1
  # DELETE /school_teacher_responses/1.json
  def destroy
    @school_teacher_response.destroy
    respond_to do |format|
      format.html { redirect_to school_teacher_responses_url, notice: 'School teacher response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_teacher_response
      @school_teacher_response = SchoolTeacherResponse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_teacher_response_params
      params.require(:school_teacher_response).permit(:school_teacher_request_id, :decision_no, :decision_year, :protocol_no, :protocol_date, :decision_duration, :decision_starting_date, :comments, :response_completed)
    end
end

staff/app/helpers/school_teacher_responses_helper.rb
module SchoolTeacherResponsesHelper
end

staff/app/views/school_teacher_responses/_edit_form.html.erb
<%= form_with(model: school_teacher_response, local: true) do |form| %>
  <% if school_teacher_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school_teacher_response.errors.count, "error") %> prohibited this school_teacher_response from being saved:</h2>

      <ul>
      <% school_teacher_response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :school_teacher_request_id %>
    <%= form.collection_select :school_teacher_request_id,
    SchoolTeacherRequest.order(:id), :id, :description,
    include_blank: false, prompt:true %>
  </div>

  <div class="field">
    <%= form.label :decision_no %>
    <%= form.number_field :decision_no, id: :school_teacher_response_decision_no %>
  </div>

  <div class="field">
    <%= form.label :decision_year %>
    <%= form.number_field :decision_year, id: :school_teacher_response_decision_year %>
  </div>

  <div class="field">
    <%= form.label :protocol_no %>
    <%= form.number_field :protocol_no, id: :school_teacher_response_protocol_no %>
  </div>

  <div class="field">
    <%= form.label :protocol_date %>
    <%= form.date_select :protocol_date, id: :school_teacher_response_protocol_date %>
  </div>

  <div class="field">
    <%= form.label :decision_duration %>
    <%= form.number_field :decision_duration, id: :school_teacher_response_decision_duration %>
  </div>

  <div class="field">
    <%= form.label :decision_starting_date %>
    <%= form.date_select :decision_starting_date, id: :school_teacher_response_decision_starting_date %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments, id: :school_teacher_response_comments %>
  </div>

  <div class="field">
    <%= form.label :response_completed %>
    <%= form.check_box :response_completed, id: :school_teacher_response_response_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff/app/views/school_teacher_responses/_form.html.erb
<%= form_with(model: school_teacher_response, local: true) do |form| %>
  <% if school_teacher_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school_teacher_response.errors.count, "error") %> prohibited this school_teacher_response from being saved:</h2>

      <ul>
      <% school_teacher_response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Επιλογή αιτήματος" %>
    <%= form.collection_select :school_teacher_request_id,
    SchoolTeacherRequest.open_cases, :id, :description,
    include_blank: false, prompt:true %>
  </div>

  <div class="field">
    <%= form.label "Αριθμός απόφασης (από το βιβλίο αποφάσεων)" %>
    <%= form.number_field :decision_no, 
      id: :school_teacher_response_decision_no,
      value: SchoolTeacherResponse.next_decision_number
    %>
  </div>

  <div class="field">
    <%= form.label "Έτος απόφασης (από το βιβλίο αποφάσεων)" %>
    <%= form.number_field :decision_year, 
      id: :school_teacher_response_decision_year,
      value: Date.today.year
    %>
  </div>

  <div class="field">
    <%= form.label "Αριθμός (εξερχόμενου) πρωτοκόλλου" %>
    <%= form.number_field :protocol_no, id: :school_teacher_response_protocol_no %>
  </div>

  <div class="field">
    <%= form.label "Ημερομηνία (εξερχόμενου) πρωτοκόλλου" %>
    <%= form.date_select :protocol_date, id: :school_teacher_response_protocol_date %>
  </div>

  <div class="field">
    <%= form.label "Διάρκεια άδειας σε μέρες" %>
    <%= form.number_field :decision_duration, id: :school_teacher_response_decision_duration %>
  </div>

  <div class="field">
    <%= form.label "Ημερομηνία έναρξης της άδειας" %>
    <%= form.date_select :decision_starting_date, id: :school_teacher_response_decision_starting_date %>
  </div>

  <div class="field">
    <%= form.label "Σχόλια" %>
    <%= form.text_area :comments, id: :school_teacher_response_comments %>
  </div>

  <div class="field">
    <%= form.label "ολοκληρωμένη" %>
    <%= form.check_box :response_completed, id: :school_teacher_response_response_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

staff/app/views/school_teacher_responses/edit.html.erb
<h1>Editing School Teacher Response</h1>

<%= render 'edit_form', school_teacher_response: @school_teacher_response %>

<%= link_to 'Show', @school_teacher_response %> |
<%= link_to 'Back', school_teacher_responses_path %>

staff/app/views/school_teacher_responses/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Αιτήματα</h1>
<!-- <h2>Open Requests</h2> -->
<table>
  <thead>
    <tr>
      <th>Καθηγητής/Καθηγήτρια</th>
      <th>Είδος άδειας</th>
      <th>Εναρξη</th>
      <th>Διάρκεια</th>
      <th>Αρχείο άδειας</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @open_school_teacher_requests.each do |school_teacher_request| %>
      <tr>
        <td><%= school_teacher_request.school_teacher %></td>
        <td><%= school_teacher_request.request_specification %></td>
        <td><%= school_teacher_request.starting_date %></td>
        <td><%= school_teacher_request.duration %></td>
        <td><%= link_to "Κατεβάστε το odt", download_request_path( school_teacher_request ) %></td>
        <td><%= link_to 'Show', school_teacher_request %></td>
        <td><%= link_to 'Edit', edit_school_teacher_request_path(school_teacher_request) %></td>
        <td><%= link_to 'Destroy', school_teacher_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>Αποφάσεις υπο δημιουργία</h1>
<!--<h1>Open School Teacher Responses (without decision files)</h1>-->

<table>
  <thead>
    <tr>
      <th>Αίτημα </th>
      <th>Αριθμός απόφασης</th>
      <th>Αριθμός πρωτοκόλλου</th>
      <th>Διάρκεια απόφασης</th>
      <th>Σχόλια</th>
      <th>Ολοκληρωμένη;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @open_school_teacher_responses.each do |school_teacher_response| %>
      <tr>
        <td><%= link_to "#{school_teacher_response.school_teacher_request.description}", 
          school_teacher_response.school_teacher_request %></td>
        <td><%= school_teacher_response.decision_no %>/<%= school_teacher_response.decision_year %></td>
        <td><%= school_teacher_response.protocol_no %>/<%= school_teacher_response.protocol_date %></td>
        <td><%= school_teacher_response.decision_duration %> day(s) starting at
        <%= school_teacher_response.decision_starting_date %></td>
        <td><%= school_teacher_response.comments %></td>
        <td><%= school_teacher_response.response_completed %></td>
        <td><%= link_to 'Show', school_teacher_response %></td>
        <td><%= link_to 'Edit', edit_school_teacher_response_path(school_teacher_response) %></td>
        <td><%= link_to 'Destroy', school_teacher_response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New School Teacher Response', new_school_teacher_response_path %> -->
<center><h1> <%= link_to 'Δημιουργία νέας απόφασης', new_school_teacher_response_path %></h1> </center>

<p align="right"><%= link_to 'αρχείο αποφάσεων', decision_files_path %></p>
<!-- <h1>Closed School Teacher Responses (with
<%= link_to 'decision files', decision_files_path %>)</h1> 

<table>
  <thead>
    <tr>
      <th>School teacher request</th>
      <th>Decision</th>
      <th>Protocol</th>
      <th>Decision duration</th>
      <th>Comments</th>
      <th>Response completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_teacher_responses_with_decision_files.each do |school_teacher_response| %>
      <tr>
        <td><%= link_to "#{school_teacher_response.school_teacher_request.description}", 
          school_teacher_response.school_teacher_request %></td>
        <td><%= school_teacher_response.decision_no %>/<%= school_teacher_response.decision_year %></td>
        <td><%= school_teacher_response.protocol_no %>/<%= school_teacher_response.protocol_date %></td>
        <td><%= school_teacher_response.decision_duration %> day(s) starting at
        <%= school_teacher_response.decision_starting_date %></td>
        <td><%= school_teacher_response.comments %></td>
        <td><%= school_teacher_response.response_completed %></td>
        <td><%= link_to 'Show', school_teacher_response %></td>
        <td><%= link_to 'Edit', edit_school_teacher_response_path(school_teacher_response) %></td>
        <td><%= link_to 'Destroy', school_teacher_response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h1>All School Teacher Responses (mainly for debugging purposes) </h1>

<table>
  <thead>
    <tr>
      <th>School teacher request</th>
      <th>Decision</th>
      <th>Protocol</th>
      <th>Decision duration</th>
      <th>Comments</th>
      <th>Response completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_teacher_responses.each do |school_teacher_response| %>
      <tr>
        <td><%= link_to "#{school_teacher_response.school_teacher_request.description}", 
          school_teacher_response.school_teacher_request %></td>
        <td><%= school_teacher_response.decision_no %>/<%= school_teacher_response.decision_year %></td>
        <td><%= school_teacher_response.protocol_no %>/<%= school_teacher_response.protocol_date %></td>
        <td><%= school_teacher_response.decision_duration %> day(s) starting at
        <%= school_teacher_response.decision_starting_date %></td>
        <td><%= school_teacher_response.comments %></td>
        <td><%= school_teacher_response.response_completed %></td>
        <td><%= link_to 'Show', school_teacher_response %></td>
        <td><%= link_to 'Edit', edit_school_teacher_response_path(school_teacher_response) %></td>
        <td><%= link_to 'Destroy', school_teacher_response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

-->

staff/app/views/school_teacher_responses/new.html.erb
<h1>Δημιουργία Νέας Απόφασης</h1>

<%= render 'form', school_teacher_response: @school_teacher_response %>

<%= link_to 'Back', school_teacher_responses_path %>

staff/app/views/school_teacher_responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School teacher request:</strong>
  <%= link_to @school_teacher_response.school_teacher_request.description,
     @school_teacher_response.school_teacher_request
  %>
</p>

<p>
  <strong>Decision no:</strong>
  <%= @school_teacher_response.decision_no %>
</p>

<p>
  <strong>Decision year:</strong>
  <%= @school_teacher_response.decision_year %>
</p>

<p>
  <strong>Protocol no:</strong>
  <%= @school_teacher_response.protocol_no %>
</p>

<p>
  <strong>Protocol date:</strong>
  <%= @school_teacher_response.protocol_date %>
</p>

<p>
  <strong>Decision duration:</strong>
  <%= @school_teacher_response.decision_duration %>
</p>

<p>
  <strong>Decision starting date:</strong>
  <%= @school_teacher_response.decision_starting_date %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @school_teacher_response.comments %>
</p>

<p>
  <strong>Response completed:</strong>
  <%= @school_teacher_response.response_completed %>
</p>

<%= link_to 'Edit', edit_school_teacher_response_path(@school_teacher_response) %> |
<%= link_to 'Back', school_teacher_responses_path %>

<hr>
<h3>Support Documents</h3>
<% if @request_support_documents %>
  <ol>
    <% @request_support_documents.each do |document| %>
      <li>
        <%= document %>
        <%= link_to '[ Διόρθωση ]', 
          edit_request_support_document_path(document) %>
        <%= link_to '[Αφαίρεση]', 
          request_support_document_path(document), 
          method: :delete %>
      </li>
    <% end %>
  </ol>
<% end %>
<p>
<%= link_to 'Add support document', add_support_document_path(@school_teacher_response.school_teacher_request) %>
</p>
<hr>
<h3>Decision</h3>
<%= link_to "Δημιουργία αρχείου απόφασης", create_decision_files_path(@school_teacher_response) %>